# Site settings
title: Meraki Project
email: clarissafchen@gmail.com
url: "http://clarissachen.com"
baseurl: "/merakiproject"
description: "This has been created as part of my job application to Cisco Meraki"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Clarissa Fonseca Chen

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ClarisFonseca
  - title: linkedin
    url: https://www.linkedin.com/in/clarissafchen/
  - title: github
    url: https://github.com/clarissafchen

# Build settings
markdown: kramdown
permalink: pretty
