# Site settings
title: Meraki Project
email: clarissafonseca1313@gmail.com
url: http://http://clarissafonseca.com
description: "This has been created as part of my job application to Cisco Meraki"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ClarisFonseca
  - title: facebook
    url: https://www.facebook.com/groups/729580157120904/
  - title: linkedin
    url: https://www.linkedin.com/in/clarissafonseca
  - title: github
    url: https://github.com/cpsf1313

# Build settings
markdown: kramdown
permalink: pretty
